[package]
name = "tensory-linalg"
edition = { workspace=true }
version = { workspace=true }
repository = { workspace=true }
authors = { workspace=true }
license = { workspace=true }

[dependencies]
tensory-core = { workspace = true }
