[package]
name = "tensory-linalg"
version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
tensory-core = { workspace = true }
