[package]
name = "tensory-core"
edition = { workspace=true }
version = { workspace=true }
repository = { workspace=true }
authors = { workspace=true }
license = { workspace=true }

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
tensory-basic = { workspace = true }

