[package]
name = "tensory-ndarray"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-linalg = { version = "0.17.0", features = ["openblas-system"] }
blas-src = { version = "0.10", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
num-traits = "0.2.19"
tensory-core = { path = "../tensory-core" }
tensory-linalg = { path = "../tensory-linalg" }


[dev-dependencies]
tensory-basic = { path = "../tensory-basic" }
num-complex = "0.4.6"
anyhow = "1.0.98"
chrono = "0.4.42"
